# Generated by Django 3.1.3 on 2024-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline_supervision_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='update_path',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
