# Generated by Django 3.1.3 on 2024-08-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline_supervision_system', '0002_auto_20240809_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='update_path',
            field=models.CharField(default='[]', max_length=2048),
        ),
    ]
