# Generated by Django 3.1.3 on 2024-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerline_supervision_system', '0003_auto_20240809_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_status',
            field=models.CharField(choices=[('not_update', 'chưa xử lý'), ('update', 'đã xử lý')], default='not_update', max_length=10, verbose_name='Defect Status'),
        ),
        migrations.AlterField(
            model_name='supervision_image',
            name='image_status',
            field=models.CharField(choices=[('normal', 'bình thường'), ('defect', 'bất thường')], default='normal', max_length=10, verbose_name='Image Status'),
        ),
        migrations.AlterField(
            model_name='supervision_image',
            name='lens_type',
            field=models.CharField(choices=[('optical', 'cam quang'), ('thermal', 'cam nhiệt')], default='optical', max_length=10, verbose_name='Lens Type'),
        ),
    ]
